# 基本站点信息
title: Yin Han
SEOTitle: Yin Han | Personal Page
description: Fighting # 站点描述
baseurl: ""                  # 如果网站在子目录中，设置子目录路径
url: "https://apple-yinhan.github.io/yin-han.github.io"  # 你的 GitHub Pages 网址
